version: '3'
services:
  kibana:
    image: kibana:7.12.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://172.16.20.22:9200

  elasticsearch:
    image: elasticsearch:7.12.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - /usr/local/elasticsearch/data:/usr/share/elasticsearch/data

  fluentd:
    build: .
    container_name: fluent/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always
    #enviroment:
    #  - ESHost=172.16.20.22
    #  - FLUENTD_CONF=fluentd.conf
    volumes:
      -  /var/log:/var/log
      -  /root/tmp/docker_fluentd/fluentd.conf:/fluentd/etc/fluentd.conf

